# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  review_status: true
  collapse_walkthrough: false
  path_filters:
    - "!crates/perfetto-trace-proto/perfetto/**"
    - "!casts/**"
    - "!screenshots/**"
  auto_review:
    enabled: true
    drafts: false
chat:
  auto_reply: true