/* automatically generated by rust-bindgen 0.69.4 */
pub use imp::*;
#[allow(dead_code)]
#[allow(non_snake_case)]
#[allow(non_camel_case_types)]
#[allow(non_upper_case_globals)]
mod imp {

pub const exec_event_flags_ERROR: exec_event_flags = 1;
pub const exec_event_flags_TOO_MANY_ITEMS: exec_event_flags = 2;
pub const exec_event_flags_COMM_READ_FAILURE: exec_event_flags = 4;
pub const exec_event_flags_POSSIBLE_TRUNCATION: exec_event_flags = 8;
pub const exec_event_flags_PTR_READ_FAILURE: exec_event_flags = 16;
pub const exec_event_flags_NO_ROOM: exec_event_flags = 32;
pub const exec_event_flags_STR_READ_FAILURE: exec_event_flags = 64;
pub const exec_event_flags_FDS_PROBE_FAILURE: exec_event_flags = 128;
pub const exec_event_flags_OUTPUT_FAILURE: exec_event_flags = 256;
pub const exec_event_flags_FLAGS_READ_FAILURE: exec_event_flags = 512;
pub const exec_event_flags_USERSPACE_DROP_MARKER: exec_event_flags = 1024;
pub type exec_event_flags = ::std::os::raw::c_uint;
}
