name: typos

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Check typos
        uses: crate-ci/typos@8a48f81b6c64dcfea44b3633223084c4be58ac5f # v1.49.0
