name: typos

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Check typos
        uses: crate-ci/typos@02ea592e44b3a53c302f697cddca7641cd051c3d # v1.45.0
