name: typos

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Check typos
        uses: crate-ci/typos@aca895bf05aec0cb7dffa6f94495e923224d9f17 # v1.46.2
